Feature/button component
isdi-coders-2023/coding-adventure-Daniel-Setien-front-202301-BCN pull request #1
Opened 2023-02-27 16:57 UTC by bigPeepo

[x] ButtonStyled
[x] Button Test
[x] Button React Component

2023-02-27 17:00 UTC, catatarelli requested changes

2023-02-27 17:00 UTC, catatarelli commented on src/components/Button/Button.test.tsx
> +      const expectedButtonText = "Sign up";
no hace falta repetir esta variable. Buscamos al button por el mismo texto que le pasamos como prop

2023-02-28 10:54 UTC, bigPeepo commented on src/components/Button/Button.test.tsx
> +      const expectedButtonText = "Sign up";
Si no hago esto no puedo romperlo...

2023-02-28 10:59 UTC, bigPeepo commented
Con feedback implementado

2023-02-28 11:13 UTC, bigPeepo commented
@MMLORENA  Holi :)

2023-02-28 11:20 UTC, MMLORENA commented on src/styles/globalStyles.css
> +@import url("@fontsource/saira-stencil-one");
¿No hay paquete npm de Saira?

2023-02-28 11:21 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +      const expectedButtonText = "Sign up";
Para romper un test puede ser también a chapa por un momento

2023-02-28 11:23 UTC, MMLORENA commented
@bigPeepo Ya tienes un test, puedes quitar del script el PassWithNoTest. 

Te recomiendo que mires el ThemeProvider pero con que me instales la fuente por npm ya me vale.

2023-02-28 11:55 UTC, bigPeepo commented
Comento por privado: no acabo de entender este ejercicio.

Se nos dice de seguir las instrucciones a pies juntillas y lo siguiente es que hagamos un Theme Provider.
Las dos primeras features tenían que ser independientes para poder mantener un flow de trabajo pero en la segunda necesitas el botón de la primera.

Sin acritud lo digo, se me ha cortado ya la mayonesa.

2023-02-28 11:59 UTC, bigPeepo commented on src/styles/globalStyles.css
> +@import url("@fontsource/saira-stencil-one");
Cambiado

2023-02-28 12:10 UTC, MMLORENA commented
> Comento por privado: no acabo de entender este ejercicio.
> 
> Se nos dice de seguir las instrucciones a pies juntillas y lo siguiente es que hagamos un Theme Provider. Las dos primeras features tenían que ser independientes para poder mantener un flow de trabajo pero en la segunda necesitas el botón de la primera.
> 
> Sin acritud lo digo, se me ha cortado ya la mayonesa.



> Comento por privado: no acabo de entender este ejercicio.
> 
> Se nos dice de seguir las instrucciones a pies juntillas y lo siguiente es que hagamos un Theme Provider. Las dos primeras features tenían que ser independientes para poder mantener un flow de trabajo pero en la segunda necesitas el botón de la primera.
> 
> Sin acritud lo digo, se me ha cortado ya la mayonesa.

El hacer un ThemeProvider era una recomendación porque te va a ayudar, no era un requisito. Y las fases son independientes, podrías haber creado un formulario sin botón y a la siguiente instanciarlo o crear uno provisional. 

Para resolverte las dudas sobre el ejercicio voy a necesitar que la pregunta sea más específica.

2023-02-28 12:10 UTC, MMLORENA approved these changes

2023-02-28 12:20 UTC, bigPeepo commented
No es una pregunta, es feedback que os doy.

2023-02-28 14:18 UTC, merged